name: Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉代码,设置最新版本 checkout@v6
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      # 安装Java 设置最新版本 setup-java@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build With Maven
        run: mvn clean install

      - name: Copy jar
        run: mvn dependency:copy -Dartifact=com.practice:ai-review:1.0 -DoutputDirectory=./libs

      - name: run jar code
        run: java -jar ./libs/ai-review-1.0-SNAPSHOT.jar
